### ISSUE TITLE
ONID_TID

### ISSUE THREAD

**Issue by EnoSat** [ciefp/ciefpsettings-enigma2#4]
why are you using incorrect values ONID and TID ?
etc.
#SERVICE 1:64:4CD:0:0:0:0:0:0:0::(TV) 11677 H 15750 3/4  420 - 440
#DESCRIPTION (TV) 11677 H 15750 3/4  420 - 440
#SERVICE 1:0:1:17E:2D9D:1A4:0:0:0:0:http%3a//0.0.0.0%3a9999/abertis/pid420:24h (País Vasco) [420]
#DESCRIPTION 24h (País Vasco) [420]
#SERVICE 1:0:1:17F:2D9D:1A4:0:0:0:0:http%3a//0.0.0.0%3a9999/abertis/pid420:24 HD (País Vasco) [420]
#DESCRIPTION 24 HD (País Vasco) [420]
#SERVICE 1:0:1:17D:2D9D:1A4:0:0:0:0:http%3a//0.0.0.0%3a9999/abertis/pid420:La 2 (País Vasco) [420]
#DESCRIPTION La 2 (País Vasco) [420]
#SERVICE 1:0:1:184:2D9D:184:0:0:0:0:http%3a//0.0.0.0%3a9999/abertis/pid420:La 2 HD RGE Nac [420]
#DESCRIPTION La 2 HD RGE Nac [420]

but right ONID/TID for 420 - ONID-**22D4** and TID-**41B** (not 1A4 and 2D9D)
![capture_001_26052022_232806](https://user-images.githubusercontent.com/4271667/170583367-1bc8d0f4-d376-4679-a774-7f3ab685db77.png)

the transponder parameters are also incorrect
![capture_001_26052022_235005](https://user-images.githubusercontent.com/4271667/170585951-ba91a60a-d9fe-463a-82af-a3064392e078.png)

**Comment by ciefp** [comment]
Nepoužívam program ts analyzátor, robím to prevodom z desiatkovej na šestnástkovú. Pri prevode frekvencie 11677 z desiatkovej na šestnástkovú vyjde = 2D9D, taktiež stream 420 pri prepočte vyjde = 1A4.Mal som chybu vo frekvencii, ale keď nastavím frekvenciu na 11675 tak mi to vyjde = 2D9B.Tak som to urobil pre všetky frekvencie.

**Comment by EnoSat** [comment]
Hi, talk about real DATA in stream ONID/TID for 420 - ONID-22D4 and TID-41B (not 1A4 and 2D9D)
check in dvbsnoop or astra-sm

**Comment by ciefp** [comment]
root@vuzero4k:~# astra --analyze http://127.0.0.1:8001/1:0:1:58C:EA64:0:CE42D9D:0:0:0                           
Sep 05 19:54:24: INFO: Starting Astra SM 0.2                                                                    
Sep 05 19:54:24: INFO: PAT: tsid: 60004                                                                         
Sep 05 19:54:24: INFO: PAT: pid: 16 NIT                                                                         
Sep 05 19:54:24: INFO: PAT: pid: 5420 PMT pnr: 1420                                                             
Sep 05 19:54:24: INFO: PAT: pid: 5421 PMT pnr: 1421                                                             
Sep 05 19:54:24: INFO: PAT: pid: 5423 PMT pnr: 1423                                                             
Sep 05 19:54:24: INFO: PAT: pid: 5431 PMT pnr: 1431                                                             
Sep 05 19:54:24: INFO: PAT: pid: 5433 PMT pnr: 1433                                                             
Sep 05 19:54:24: INFO: PAT: pid: 8100 PMT pnr: 65534                                                            
Sep 05 19:54:24: INFO: PAT: pid: 5440 PMT pnr: 1440                                                             
Sep 05 19:54:24: INFO: PAT: crc32: 0x136DCE03                                                                   
Sep 05 19:54:25: INFO: Bitrate: 9240 Kbit/s                                                                     
Sep 05 19:54:25: INFO: PMT: pnr: 1420                                                                           
Sep 05 19:54:25: INFO: PMT: pid: 8191 PCR                                                                       
Sep 05 19:54:25: INFO: PMT: CAS: caid: 0x2600 pid: 8191                                                         
Sep 05 19:54:25: INFO: PMT: Service: HS88U.20                                                                   
Sep 05 19:54:25: INFO: PMT: Provider: HSA-88U                                                                   
Sep 05 19:54:25: INFO: DATA: pid: 420 type: User private (0x90)                                                 
Sep 05 19:54:25: INFO: DATA: descriptor: 0xFB06000C00000000                                                     
Sep 05 19:54:25: INFO: DATA: descriptor: 0xFA08000C000000004000                                                 
Sep 05 19:54:25: INFO: PMT: crc32: 0x39D4596E                                                                   
Sep 05 19:54:26: INFO: Bitrate: 11053 Kbit/s  

#SERVICE 1:0:1:17E:2D9B:1A4:0:0:0:0:
#SERVICE 1:0:1:onid-tid:frequency:pid:0:0:0:0:
hex to decimal:
17E = 382 = onid tid
2D9B = 11675 = frequency
14A = 420 = pid

**Comment by EnoSat** [comment]
make_channel({
  name = "Abertis PID 301",
  input = {
    "http://localhost:8001/1:0:1:515:EA63:0:CE42D85:0:0:0:",
  },
  transform = {{
    format = "pipe",
      command = "/etc/astra/scripts/abertis 301",
  }},
  output = {
    "http://localhost:9999/abertis/pid301",
  },
})

tsid: 60003 = TID-EA63
root@mutant51:~# astra --analyze http://127.0.0.1:8001/1:0:1:515:EA63:0:CE42D85:0:0:0
Sep 05 21:43:46: INFO: Starting Astra SM 0.2
Sep 05 21:43:47: INFO: PAT: tsid: 60003
Sep 05 21:43:47: INFO: PAT: pid: 16 NIT
Sep 05 21:43:47: INFO: PAT: pid: 5301 PMT pnr: 1301
Sep 05 21:43:47: INFO: PAT: pid: 5303 PMT pnr: 1303
Sep 05 21:43:47: INFO: PAT: pid: 8100 PMT pnr: 65534
Sep 05 21:43:47: INFO: PAT: crc32: 0x8F31AF93
Sep 05 21:43:47: INFO: Bitrate: 20021 Kbit/s
Sep 05 21:43:48: INFO: Bitrate: 20021 Kbit/s
Sep 05 21:43:49: INFO: Bitrate: 20021 Kbit/s

tsid: 1007 = TID-**3EF**
root@mutant51:~# astra --analyze http://127.0.0.1:9999/abertis/pid301
Sep 05 21:47:44: INFO: Starting Astra SM 0.2
Sep 05 21:47:45: INFO: PAT: tsid: 1007
Sep 05 21:47:45: INFO: PAT: pid: 16 NIT
Sep 05 21:47:45: INFO: PAT: pid: 100 PMT pnr: 480
Sep 05 21:47:45: INFO: PAT: pid: 200 PMT pnr: 481
Sep 05 21:47:45: INFO: PAT: pid: 1000 PMT pnr: 482
Sep 05 21:47:45: INFO: PAT: pid: 1500 PMT pnr: 483
Sep 05 21:47:45: INFO: PAT: pid: 300 PMT pnr: 484
Sep 05 21:47:45: INFO: PAT: pid: 2000 PMT pnr: 485
Sep 05 21:47:45: INFO: PAT: pid: 2030 PMT pnr: 486
Sep 05 21:47:45: INFO: PAT: pid: 2040 PMT pnr: 487
Sep 05 21:47:45: INFO: PAT: pid: 400 PMT pnr: 488
Sep 05 21:47:45: INFO: PAT: crc32: 0x5038C2AC
Sep 05 21:47:45: INFO: PMT: pnr: 484
Sep 05 21:47:45: INFO: PMT: pid: 301 PCR
Sep 05 21:47:45: INFO: SUB: pid: 102 type: Private PES, ISO/IEC 13818-1 (0x06)
Sep 05 21:47:45: INFO: SUB: Stream ID: 2
Sep 05 21:47:45: INFO: SUB: type: teletext
Sep 05 21:47:45: INFO: SUB:    page: 100 (initial page), language: spa
Sep 05 21:47:45: INFO: SUB:    page: 088 (subtitle page), language: spa
Sep 05 21:47:45: INFO: SUB:    page: 089 (subtitle page), language: qaa
Sep 05 21:47:45: INFO: DATA: pid: 115 type: Private sections, ISO/IEC 13818-1 (0x05)
Sep 05 21:47:45: INFO: DATA: Stream ID: 21
Sep 05 21:47:45: INFO: DATA: descriptor: 0x6F030010F6
Sep 05 21:47:45: INFO: VIDEO: pid: 301 type: MPEG-4 AVC/H.264, ISO/IEC 14496-10 (0x1B)
Sep 05 21:47:45: INFO: VIDEO: Stream ID: 1
Sep 05 21:47:45: INFO: VIDEO: descriptor: 0x060102
Sep 05 21:47:45: INFO: VIDEO: descriptor: 0x28046400283F
Sep 05 21:47:45: INFO: DATA: pid: 302 type: Private PES, ISO/IEC 13818-1 (0x06)
Sep 05 21:47:45: INFO: DATA: Stream ID: 3
Sep 05 21:47:45: INFO: DATA: Language: spa
Sep 05 21:47:45: INFO: DATA: descriptor: 0x7A03C0C210
Sep 05 21:47:45: INFO: DATA: pid: 303 type: Private PES, ISO/IEC 13818-1 (0x06)
Sep 05 21:47:45: INFO: DATA: Stream ID: 4
Sep 05 21:47:45: INFO: DATA: Language: qaa
Sep 05 21:47:45: INFO: DATA: descriptor: 0x7A03C0C210
Sep 05 21:47:45: INFO: DATA: pid: 304 type: Private PES, ISO/IEC 13818-1 (0x06)
Sep 05 21:47:45: INFO: DATA: Stream ID: 5
Sep 05 21:47:45: INFO: DATA: Language: spa
Sep 05 21:47:45: INFO: DATA: descriptor: 0x7A03C09010
Sep 05 21:47:45: INFO: SUB: pid: 311 type: Private PES, ISO/IEC 13818-1 (0x06)
Sep 05 21:47:45: INFO: SUB: Stream ID: 11
Sep 05 21:47:45: INFO: SUB: descriptor: 0x59087370611000010001
Sep 05 21:47:45: INFO: PMT: crc32: 0x8C103C7
Sep 05 21:47:45: INFO: PMT: pnr: 482
Sep 05 21:47:45: INFO: PMT: pid: 1001 PCR
Sep 05 21:47:45: INFO: VIDEO: pid: 1001 type: MPEG-2 video, ISO/IEC 13818-2 (0x02)
Sep 05 21:47:45: INFO: VIDEO: Stream ID: 1
Sep 05 21:47:45: INFO: VIDEO: descriptor: 0x02031A485F
Sep 05 21:47:45: INFO: VIDEO: descriptor: 0x060102
Sep 05 21:47:45: INFO: SUB: pid: 1002 type: Private PES, ISO/IEC 13818-1 (0x06)
Sep 05 21:47:45: INFO: SUB: Stream ID: 2
Sep 05 21:47:45: INFO: SUB: type: teletext
Sep 05 21:47:45: INFO: SUB:    page: 100 (initial page), language: spa
Sep 05 21:47:45: INFO: SUB:    page: 088 (subtitle page), language: spa
Sep 05 21:47:45: INFO: AUDIO: pid: 1003 type: MPEG-1 audio, ISO/IEC 11172-3 (0x03)
Sep 05 21:47:45: INFO: AUDIO: Stream ID: 3
Sep 05 21:47:45: INFO: AUDIO: Language: spa
Sep 05 21:47:45: INFO: AUDIO: descriptor: 0x030167
Sep 05 21:47:45: INFO: AUDIO: pid: 1004 type: MPEG-1 audio, ISO/IEC 11172-3 (0x03)
Sep 05 21:47:45: INFO: AUDIO: Stream ID: 4
Sep 05 21:47:45: INFO: AUDIO: Language: qaa
Sep 05 21:47:45: INFO: AUDIO: descriptor: 0x030167
Sep 05 21:47:45: INFO: AUDIO: pid: 1005 type: MPEG-1 audio, ISO/IEC 11172-3 (0x03)
Sep 05 21:47:45: INFO: AUDIO: Stream ID: 5
Sep 05 21:47:45: INFO: AUDIO: Language: spa
Sep 05 21:47:45: INFO: AUDIO: descriptor: 0x030167
Sep 05 21:47:45: INFO: SUB: pid: 1011 type: Private PES, ISO/IEC 13818-1 (0x06)
Sep 05 21:47:45: INFO: SUB: Stream ID: 11
Sep 05 21:47:45: INFO: SUB: descriptor: 0x59087370611000010001
Sep 05 21:47:45: INFO: DATA: pid: 1015 type: Private sections, ISO/IEC 13818-1 (0x05)
Sep 05 21:47:45: INFO: DATA: Stream ID: 21
Sep 05 21:47:45: INFO: DATA: descriptor: 0x6F030010F6
Sep 05 21:47:45: INFO: PMT: crc32: 0x5975D1DF
Sep 05 21:47:45: INFO: PMT: pnr: 485
Sep 05 21:47:45: INFO: PMT: pid: 2001 PCR
Sep 05 21:47:45: INFO: AUDIO: pid: 2001 type: MPEG-1 audio, ISO/IEC 11172-3 (0x03)
Sep 05 21:47:45: INFO: AUDIO: Language: spa
Sep 05 21:47:45: INFO: AUDIO: Stream ID: 1
Sep 05 21:47:45: INFO: AUDIO: Maximum bitrate: 357
Sep 05 21:47:45: INFO: DATA: pid: 2005 type: Private sections, ISO/IEC 13818-1 (0x05)
Sep 05 21:47:45: INFO: DATA: Stream ID: 50
Sep 05 21:47:45: INFO: DATA: descriptor: 0x6F030010F6
Sep 05 21:47:45: INFO: PMT: crc32: 0x43CEA1B4
Sep 05 21:47:45: INFO: PMT: pnr: 481
Sep 05 21:47:45: INFO: PMT: pid: 201 PCR
Sep 05 21:47:45: INFO: VIDEO: pid: 201 type: MPEG-2 video, ISO/IEC 13818-2 (0x02)
Sep 05 21:47:45: INFO: VIDEO: Stream ID: 1
Sep 05 21:47:45: INFO: VIDEO: descriptor: 0x02031A485F
Sep 05 21:47:45: INFO: VIDEO: descriptor: 0x060102
Sep 05 21:47:45: INFO: SUB: pid: 202 type: Private PES, ISO/IEC 13818-1 (0x06)
Sep 05 21:47:45: INFO: SUB: Stream ID: 2
Sep 05 21:47:45: INFO: SUB: type: teletext
Sep 05 21:47:45: INFO: SUB:    page: 100 (initial page), language: spa
Sep 05 21:47:45: INFO: SUB:    page: 088 (subtitle page), language: spa
Sep 05 21:47:45: INFO: SUB:    page: 089 (subtitle page), language: qaa
Sep 05 21:47:45: INFO: AUDIO: pid: 203 type: MPEG-1 audio, ISO/IEC 11172-3 (0x03)
Sep 05 21:47:45: INFO: AUDIO: Stream ID: 3
Sep 05 21:47:45: INFO: AUDIO: Language: spa
Sep 05 21:47:45: INFO: AUDIO: descriptor: 0x030167
Sep 05 21:47:45: INFO: AUDIO: pid: 204 type: MPEG-1 audio, ISO/IEC 11172-3 (0x03)
Sep 05 21:47:45: INFO: AUDIO: Stream ID: 4
Sep 05 21:47:45: INFO: AUDIO: Language: qaa
Sep 05 21:47:45: INFO: AUDIO: descriptor: 0x030167
Sep 05 21:47:45: INFO: AUDIO: pid: 205 type: MPEG-1 audio, ISO/IEC 11172-3 (0x03)
Sep 05 21:47:45: INFO: AUDIO: Stream ID: 5
Sep 05 21:47:45: INFO: AUDIO: Language: spa
Sep 05 21:47:45: INFO: AUDIO: descriptor: 0x030167
Sep 05 21:47:45: INFO: SUB: pid: 211 type: Private PES, ISO/IEC 13818-1 (0x06)
Sep 05 21:47:45: INFO: SUB: Stream ID: 11
Sep 05 21:47:45: INFO: SUB: descriptor: 0x59087370611000010001
Sep 05 21:47:45: INFO: DATA: pid: 215 type: Private sections, ISO/IEC 13818-1 (0x05)
Sep 05 21:47:45: INFO: DATA: Stream ID: 21
Sep 05 21:47:45: INFO: DATA: descriptor: 0x6F030010F6
Sep 05 21:47:45: INFO: PMT: crc32: 0x3E89F69D
Sep 05 21:47:45: INFO: PMT: pnr: 486
Sep 05 21:47:45: INFO: PMT: pid: 2031 PCR
Sep 05 21:47:45: INFO: AUDIO: pid: 2031 type: MPEG-1 audio, ISO/IEC 11172-3 (0x03)
Sep 05 21:47:45: INFO: AUDIO: Language: spa
Sep 05 21:47:45: INFO: AUDIO: Stream ID: 1
Sep 05 21:47:45: INFO: AUDIO: Maximum bitrate: 357
Sep 05 21:47:45: INFO: DATA: pid: 2035 type: Private sections, ISO/IEC 13818-1 (0x05)
Sep 05 21:47:45: INFO: DATA: descriptor: 0x6F030010F6
Sep 05 21:47:45: INFO: PMT: crc32: 0xEBF4D8A3
Sep 05 21:47:45: INFO: PMT: pnr: 483
Sep 05 21:47:45: INFO: PMT: pid: 1501 PCR
Sep 05 21:47:45: INFO: SUB: pid: 1002 type: Private PES, ISO/IEC 13818-1 (0x06)
Sep 05 21:47:45: INFO: SUB: Stream ID: 2
Sep 05 21:47:45: INFO: SUB: type: teletext
Sep 05 21:47:45: INFO: SUB:    page: 100 (initial page), language: spa
Sep 05 21:47:45: INFO: SUB:    page: 088 (subtitle page), language: spa
Sep 05 21:47:45: INFO: DATA: pid: 1015 type: Private sections, ISO/IEC 13818-1 (0x05)
Sep 05 21:47:45: INFO: DATA: Stream ID: 21
Sep 05 21:47:45: INFO: DATA: descriptor: 0x6F030010F6
Sep 05 21:47:45: INFO: VIDEO: pid: 1501 type: MPEG-4 AVC/H.264, ISO/IEC 14496-10 (0x1B)
Sep 05 21:47:45: INFO: VIDEO: Stream ID: 1
Sep 05 21:47:45: INFO: VIDEO: descriptor: 0x02031A445F
Sep 05 21:47:45: INFO: VIDEO: descriptor: 0x060102
Sep 05 21:47:45: INFO: VIDEO: descriptor: 0x28046400283F
Sep 05 21:47:45: INFO: DATA: pid: 1503 type: Private PES, ISO/IEC 13818-1 (0x06)
Sep 05 21:47:45: INFO: DATA: Stream ID: 3
Sep 05 21:47:45: INFO: DATA: Language: spa
Sep 05 21:47:45: INFO: DATA: descriptor: 0x7A03C0C210
Sep 05 21:47:45: INFO: DATA: pid: 1504 type: Private PES, ISO/IEC 13818-1 (0x06)
Sep 05 21:47:45: INFO: DATA: Stream ID: 4
Sep 05 21:47:45: INFO: DATA: Language: qaa
Sep 05 21:47:45: INFO: DATA: descriptor: 0x7A03C0C010
Sep 05 21:47:45: INFO: DATA: pid: 1505 type: Private PES, ISO/IEC 13818-1 (0x06)
Sep 05 21:47:45: INFO: DATA: Stream ID: 5
Sep 05 21:47:45: INFO: DATA: Language: spa
Sep 05 21:47:45: INFO: DATA: descriptor: 0x7A03C09010
Sep 05 21:47:45: INFO: SUB: pid: 1511 type: Private PES, ISO/IEC 13818-1 (0x06)
Sep 05 21:47:45: INFO: SUB: Stream ID: 11
Sep 05 21:47:45: INFO: SUB: descriptor: 0x59087370611000010001
Sep 05 21:47:45: INFO: PMT: crc32: 0xA4F8684A
Sep 05 21:47:45: INFO: PMT: pnr: 487
Sep 05 21:47:45: INFO: PMT: pid: 2041 PCR
Sep 05 21:47:45: INFO: DATA: pid: 2035 type: Private sections, ISO/IEC 13818-1 (0x05)
Sep 05 21:47:45: INFO: DATA: descriptor: 0x6F030010F6
Sep 05 21:47:45: INFO: AUDIO: pid: 2041 type: MPEG-1 audio, ISO/IEC 11172-3 (0x03)
Sep 05 21:47:45: INFO: AUDIO: Language: spa
Sep 05 21:47:45: INFO: AUDIO: Stream ID: 1
Sep 05 21:47:45: INFO: AUDIO: Maximum bitrate: 357
Sep 05 21:47:45: INFO: PMT: crc32: 0xD5DF0863
Sep 05 21:47:45: INFO: PMT: pnr: 488
Sep 05 21:47:45: INFO: PMT: pid: 401 PCR
Sep 05 21:47:45: INFO: SUB: pid: 202 type: Private PES, ISO/IEC 13818-1 (0x06)
Sep 05 21:47:45: INFO: SUB: Stream ID: 2
Sep 05 21:47:45: INFO: SUB: type: teletext
Sep 05 21:47:45: INFO: SUB:    page: 100 (initial page), language: spa
Sep 05 21:47:45: INFO: SUB:    page: 088 (subtitle page), language: spa
Sep 05 21:47:45: INFO: SUB:    page: 089 (subtitle page), language: qaa
Sep 05 21:47:45: INFO: DATA: pid: 215 type: Private sections, ISO/IEC 13818-1 (0x05)
Sep 05 21:47:45: INFO: DATA: Stream ID: 21
Sep 05 21:47:45: INFO: DATA: descriptor: 0x6F030010F6
Sep 05 21:47:45: INFO: VIDEO: pid: 401 type: MPEG-4 AVC/H.264, ISO/IEC 14496-10 (0x1B)
Sep 05 21:47:45: INFO: VIDEO: Stream ID: 1
Sep 05 21:47:45: INFO: VIDEO: descriptor: 0x02031A445F
Sep 05 21:47:45: INFO: VIDEO: descriptor: 0x060102
Sep 05 21:47:45: INFO: VIDEO: descriptor: 0x28046400283F
Sep 05 21:47:45: INFO: DATA: pid: 402 type: Private PES, ISO/IEC 13818-1 (0x06)
Sep 05 21:47:45: INFO: DATA: Stream ID: 3
Sep 05 21:47:45: INFO: DATA: Language: spa
Sep 05 21:47:45: INFO: DATA: descriptor: 0x7A03C0C210
Sep 05 21:47:45: INFO: DATA: pid: 403 type: Private PES, ISO/IEC 13818-1 (0x06)
Sep 05 21:47:45: INFO: DATA: Stream ID: 4
Sep 05 21:47:45: INFO: DATA: Language: qaa
Sep 05 21:47:45: INFO: DATA: descriptor: 0x7A03C0C210
Sep 05 21:47:45: INFO: DATA: pid: 404 type: Private PES, ISO/IEC 13818-1 (0x06)
Sep 05 21:47:45: INFO: DATA: Stream ID: 5
Sep 05 21:47:45: INFO: DATA: Language: spa
Sep 05 21:47:45: INFO: DATA: descriptor: 0x7A03C09010
Sep 05 21:47:45: INFO: SUB: pid: 411 type: Private PES, ISO/IEC 13818-1 (0x06)
Sep 05 21:47:45: INFO: SUB: Stream ID: 11
Sep 05 21:47:45: INFO: SUB: descriptor: 0x59087370611000010001
Sep 05 21:47:45: INFO: PMT: crc32: 0xBC3C020B
Sep 05 21:47:45: INFO: PMT: pnr: 480
Sep 05 21:47:45: INFO: PMT: pid: 101 PCR
Sep 05 21:47:45: INFO: VIDEO: pid: 101 type: MPEG-2 video, ISO/IEC 13818-2 (0x02)
Sep 05 21:47:45: INFO: VIDEO: Stream ID: 1
Sep 05 21:47:45: INFO: VIDEO: descriptor: 0x02031A485F
Sep 05 21:47:45: INFO: VIDEO: descriptor: 0x060102
Sep 05 21:47:45: INFO: SUB: pid: 102 type: Private PES, ISO/IEC 13818-1 (0x06)
Sep 05 21:47:45: INFO: SUB: Stream ID: 2
Sep 05 21:47:45: INFO: SUB: type: teletext
Sep 05 21:47:45: INFO: SUB:    page: 100 (initial page), language: spa
Sep 05 21:47:45: INFO: SUB:    page: 088 (subtitle page), language: spa
Sep 05 21:47:45: INFO: SUB:    page: 089 (subtitle page), language: qaa
Sep 05 21:47:45: INFO: AUDIO: pid: 103 type: MPEG-1 audio, ISO/IEC 11172-3 (0x03)
Sep 05 21:47:45: INFO: AUDIO: Stream ID: 3
Sep 05 21:47:45: INFO: AUDIO: Language: spa
Sep 05 21:47:45: INFO: AUDIO: descriptor: 0x030167
Sep 05 21:47:45: INFO: AUDIO: pid: 104 type: MPEG-1 audio, ISO/IEC 11172-3 (0x03)
Sep 05 21:47:45: INFO: AUDIO: Stream ID: 4
Sep 05 21:47:45: INFO: AUDIO: Language: qaa
Sep 05 21:47:45: INFO: AUDIO: descriptor: 0x030167
Sep 05 21:47:45: INFO: AUDIO: pid: 105 type: MPEG-1 audio, ISO/IEC 11172-3 (0x03)
Sep 05 21:47:45: INFO: AUDIO: Stream ID: 5
Sep 05 21:47:45: INFO: AUDIO: Language: spa
Sep 05 21:47:45: INFO: AUDIO: descriptor: 0x030167
Sep 05 21:47:45: INFO: SUB: pid: 111 type: Private PES, ISO/IEC 13818-1 (0x06)
Sep 05 21:47:45: INFO: SUB: Stream ID: 11
Sep 05 21:47:45: INFO: SUB: descriptor: 0x59087370611000010001
Sep 05 21:47:45: INFO: DATA: pid: 115 type: Private sections, ISO/IEC 13818-1 (0x05)
Sep 05 21:47:45: INFO: DATA: Stream ID: 21
Sep 05 21:47:45: INFO: DATA: descriptor: 0x6F030010F6
Sep 05 21:47:45: INFO: PMT: crc32: 0x4DC899D2
Sep 05 21:47:45: INFO: Bitrate: 16257 Kbit/s
Sep 05 21:47:46: INFO: SDT: tsid: 1007
Sep 05 21:47:46: INFO: SDT: sid: 480
Sep 05 21:47:46: INFO: SDT:    Service: La 1
Sep 05 21:47:46: INFO: SDT:    Provider: RTVE
Sep 05 21:47:46: INFO: SDT: sid: 481
Sep 05 21:47:46: INFO: SDT:    Service: La 2
Sep 05 21:47:46: INFO: SDT:    Provider: RTVE
Sep 05 21:47:46: INFO: SDT: sid: 482
Sep 05 21:47:46: INFO: SDT:    Service: 24h
Sep 05 21:47:46: INFO: SDT:    Provider: RTVE
Sep 05 21:47:46: INFO: SDT: sid: 483
Sep 05 21:47:46: INFO: SDT:    Service: 24h HD
Sep 05 21:47:46: INFO: SDT:    Provider: RTVE
Sep 05 21:47:46: INFO: SDT: sid: 484
Sep 05 21:47:46: INFO: SDT:    Service: La 1 HD
Sep 05 21:47:46: INFO: SDT:    Provider: RTVE
Sep 05 21:47:46: INFO: SDT: sid: 485
Sep 05 21:47:46: INFO: SDT:    Service: RNE Canarias
Sep 05 21:47:46: INFO: SDT:    Provider: RTVE
Sep 05 21:47:46: INFO: SDT: sid: 486
Sep 05 21:47:46: INFO: SDT:    Service: Radio 5 RNE Tenerife
Sep 05 21:47:46: INFO: SDT:    Provider: RTVE
Sep 05 21:47:46: INFO: SDT: sid: 487
Sep 05 21:47:46: INFO: SDT:    Service: Radio 5 RNE Las Palmas
Sep 05 21:47:46: INFO: SDT:    Provider: RTVE
Sep 05 21:47:46: INFO: SDT: sid: 488
Sep 05 21:47:46: INFO: SDT:    Service: La 2 HD
Sep 05 21:47:46: INFO: SDT:    Provider: RTVE
Sep 05 21:47:46: INFO: SDT: crc32: 0x13FD5A80
Sep 05 21:47:46: INFO: Bitrate: 21180 Kbit/s

or better send stream from astra-sm http://localhost:9999/abertis/pid301 to some stream analyzator for view correct all ID
<img width="443" alt="capture_001_06092022_005137" src="https://user-images.githubusercontent.com/4271667/188518561-75e454dd-0b73-4431-95ab-07ce649cba99.png">
